name: scrape network configs

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  scheduled:
    runs-on: [self-hosted, atc-runners]
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch latest configs
      run: |-
        python retrieve_configs.py
      env:
        SSH_AUTH_USERNAME: ${{ secrets.SSH_AUTH_USERNAME }}
        SSH_AUTH_PASSWORD: ${{ secrets.SSH_AUTH_PASSWORD }}

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
